# Ubuntu specific worker kubeadm config
preKubeadmCommands:
  - netplan apply
  - systemctl enable --now crio kubelet
files:
  - path : /etc/netplan/52-ironicendpoint.yaml
    owner: root:root
    permissions: '0644'
    content: |
      network:
        version: 2
        renderer: networkd
        bridges:
          {{ IRONIC_ENDPOINT_BRIDGE }}:
            interfaces: [ens3]
            addresses:
            - {{ "{{ ds.meta_data.provisioningIP }}" }}/{{ "{{ ds.meta_data.provisioningCIDR }}" }}
  - path : /etc/containers/registries.conf
    content: |
       [registries.search]
       registries = ['docker.io']

       [registries.insecure]
       registries = ['{{ REGISTRY }}']
